### ISSUE TITLE
No input when using shared libraries.

### ISSUE THREAD

**Issue by ionenwks** [quakeforge/quakeforge#20]
Using a minimal current build at https://github.com/quakeforge/quakeforge/commit/f7efcde7ab43cc3eb808e73df71a5e2c46a21460 on Linux and trying with nq-x11 (e.g. can't open the menu/console).

Haven't bisected but I do assume it's related to https://github.com/quakeforge/quakeforge/commit/e81d690b51dc219518078cad6123576f21b50bad

No issues if reverting to --enable-static.

**Comment by taniwha** [comment]
I think I fixed this in e089234f3819e193dc337352c9069f17fc2f0405 and e799a7ae45b0ab2ad7b642953277db8ccf256cf8. It's working here *now* (absolutely was not before those commits, though). Please confirm.

**Comment by ionenwks** [comment]
Yep, https://github.com/quakeforge/quakeforge/commit/e799a7ae45b0ab2ad7b642953277db8ccf256cf8 is working as expected. Thanks.
