### ISSUE TITLE
Implement global fog.

### ISSUE THREAD

**Issue by taniwha** [quakeforge/quakeforge#71]
Getting it to work nicely with real-time lights (in particular, volumetrics) is probably out-of-scope, but even some basics should make a nice difference.

**Comment by dsvensson** [comment]
This book is pretty nice, and has a chapter on this topic, but not sure about the relevancy as it seems you're taking a different route than the renderer laid out in the book. I haven't come far enough in my pet project to see how it interacts with lighting though. :man_shrugging: 

https://www.packtpub.com/product/mastering-graphics-programming-with-vulkan/9781803244792

**Comment by taniwha** [comment]
Hmm, thanks. I have mixed feelings about Packt (fairly good info, horrible navigation). I've got fog working in both forward (simple blend) and deferred (a bit of transmission for lighting of surfaces: 8f20638cd) but I should probably get the book anyway. I have plans for taking QF beyond quake, so such is likely to be highly relevant in the future.
